# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.3-snapshot-1
	loader_version=0.19.3

# Mod Properties
	mod_version = 4.1.2+26.3
	maven_group = com.minenash
	archives_base_name = custom_hud

# Dependencies
	#Fabric api
	fabric_version=0.153.1+26.3
	modmenu_version=20.0.0-beta.4
